### ISSUE TITLE
非http包进入到http协议解码，不抛出BadSchema，反而bad-request进入到encodeResponse抛出空指针了

### ISSUE THREAD

**Issue by dhhua** [baidu/brpc-java#104]
java.lang.NullPointerException: null
	at com.baidu.brpc.protocol.http.HttpRpcProtocol.encodeResponse(HttpRpcProtocol.java:410) ~[brpc-java-2.5.1.jar:na]
	at com.baidu.brpc.server.handler.DecodeWorkTask.run(DecodeWorkTask.java:130) ~[brpc-java-2.5.1.jar:na]
	at com.baidu.brpc.utils.ThreadPool.consume(ThreadPool.java:130) [brpc-java-2.5.1.jar:na]
	at com.baidu.brpc.utils.ThreadPool.access$000(ThreadPool.java:37) [brpc-java-2.5.1.jar:na]
	at com.baidu.brpc.utils.ThreadPool$1.run(ThreadPool.java:78) [brpc-java-2.5.1.jar:na]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.36.Final.jar:4.1.36.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]

**Comment by dhhua** [comment]
http协议不应该是    
@Override
  public boolean isCoexistence() {
        return true;
    }
的吧

**Comment by wenweihu86** [comment]
@dhhua http协议是可以和已存在的其他协议共存的，比如可用于brpc标准协议和http协议并存。
你出现的这个错误，可以给下详细的复现方法或者代码吗？

**Comment by dhhua** [comment]
@wenweihu86 我是写了自定义一些，而且要和brpc协议并存，原本写的优先级比较低，接收的包在httpProtocol就报错了，还没到自定义协议解包，现在我是调高优先级解决了，建议以后可以配置要使用的protocol,现在只能配一个主协议，配了就只能用单协议了，不过就是可以用多端口解决，多端口注册服务对我这边不太好

**Comment by dhhua** [comment]
> @wenweihu86 我是写了自定义协议，而且要和brpc协议并存，原本写的优先级比较低，接收的包在httpProtocol就报错了，还没到自定义协议解包，现在我是调高优先级解决了，建议以后可以配置要使用的protocol,现在只能配一个主协议，配了就只能用单协议了，不过就是可以用多端口解决，多端口注册服务对我这边不太好

**Comment by wenweihu86** [comment]
@dhhua 在httpProtocol报错了，HttpRpcProtocol.decode返回BadSchema的呀。
支持配置多个协议，确实会有这个需求，后续会支持。

**Comment by dhhua** [comment]
@wenweihu86 BrpcHttpObjectDecoder在decode的时候用了HttpObjectDecoder，HttpObjectDecoder把异常直接捕获返回了bad-request了，所以不会抛出BadSchema
