### ISSUE TITLE
运行 com.baidu.brpc.example.http.json.RpcServerTest 一段时间后抛出了 NPE

### ISSUE THREAD

**Issue by wlingxiao** [baidu/brpc-java#142]
https://github.com/baidu/brpc-java/blob/d27a612133ec4295abb6ee7daae20144393ceed8/brpc-java-core/src/main/java/com/baidu/brpc/protocol/http/HttpRpcProtocol.java#L356

http request 中 content-type 请求头为空导致 NPE，是否应该进行非空检测？还是其它处理方法？

**Comment by wlingxiao** [comment]
重启了一次之后，过去了半小时未能复现此问题

**Comment by wenweihu86** [comment]
@wlingxiao 最好应该加个非空检测，方便的话，可以提个pr帮助修复。

**Comment by wlingxiao** [comment]
@wenweihu86 如果允许content-type 为 null，这里没法处理

https://github.com/baidu/brpc-java/blob/d27a612133ec4295abb6ee7daae20144393ceed8/brpc-java-core/src/main/java/com/baidu/brpc/protocol/http/HttpRpcProtocol.java#L358

**Comment by wenweihu86** [comment]
@wlingxiao content-type不允许为空的。

**Comment by wlingxiao** [comment]
@wenweihu86 我启动服务器，随意访问一个地址报错了，列如 `http://localhost:8080/hello`

```java
2019-11-26 17:35:46,270 [server-work-thread-1] WARN  com.baidu.brpc.server.handler.DecodeWorkTask - decode request failed:
java.lang.NullPointerException: null
	at com.baidu.brpc.protocol.http.HttpRpcProtocol.decodeRequest(HttpRpcProtocol.java:356)
	at com.baidu.brpc.server.handler.DecodeWorkTask.run(DecodeWorkTask.java:117)
	at com.baidu.brpc.utils.ThreadPool.consume(ThreadPool.java:131)
	at com.baidu.brpc.utils.ThreadPool.access$000(ThreadPool.java:37)
	at com.baidu.brpc.utils.ThreadPool$1.run(ThreadPool.java:79)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2019-11-26 17:35:46,270 [server-work-thread-1] WARN  com.baidu.brpc.server.handler.DecodeWorkTask - send response failed:
java.lang.NullPointerException: null
	at com.baidu.brpc.protocol.http.HttpRpcProtocol.encodeResponse(HttpRpcProtocol.java:431)
	at com.baidu.brpc.server.handler.DecodeWorkTask.run(DecodeWorkTask.java:130)
	at com.baidu.brpc.utils.ThreadPool.consume(ThreadPool.java:131)
	at com.baidu.brpc.utils.ThreadPool.access$000(ThreadPool.java:37)
	at com.baidu.brpc.utils.ThreadPool$1.run(ThreadPool.java:79)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

应该是 https://github.com/baidu/brpc-java/blob/98eebffdc6ba8b44dac9b4997fb018f9d3a16e1d/brpc-java-core/src/main/java/com/baidu/brpc/server/handler/DecodeWorkTask.java#L69 
https://github.com/baidu/brpc-java/blob/98eebffdc6ba8b44dac9b4997fb018f9d3a16e1d/brpc-java-core/src/main/java/com/baidu/brpc/server/handler/DecodeWorkTask.java#L83
这个 if 没有处理其它情况

**Comment by wenweihu86** [comment]
@wlingxiao 不应该在这个if分支处理，应该在HttpRpcProtocol里处理。

**Comment by wenweihu86** [comment]
fixed by #151
