### ISSUE TITLE
已经用protoc工具生成包了怎么使用

### ISSUE THREAD

**Issue by Delostik** [baidu/brpc-java#173]
我们这边proto已经用protoc-gen-grpc-java打成了一个包（是proto3的），以前用grpc的时候可以直接加载这个包，然后newBlockingStub(channel).echo(request)来调用。

要切成brpc，还能用这个打好的包吗

**Comment by wenweihu86** [comment]
@Delostik Request Response可以复用的，interface需要自己定义。

**Comment by Delostik** [comment]
@wenweihu86 看起来应该就是写一个interface，然后把原来的getstub改成用brpc的service就好了……
但是一直在报下面这个错误。我们有鉴权的interceptor，在服务端看到已经连上来并且鉴权成功了。但是服务端没收到request……
com.baidu.brpc.exceptions.RpcException: unknown error
	at com.baidu.brpc.client.BrpcProxy.executeWithRetry(BrpcProxy.java:299) 
	at com.baidu.brpc.client.BrpcProxy.intercept(BrpcProxy.java:248) 
	at com.echo.test.TestService$$EnhancerByCGLIB$$95d41fbd.Ping(<generated>) 
	at com.echo.test.client.ping(Cleint.java:78)

**Comment by Delostik** [comment]
的确是替换request、response，再定义interface就可以，之前遇到的问题是interceptor有问题，感谢
